[package]
name = "my-json"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yft-extensions = { tag = "0.1.1", git = "https://github.com/ITYFT/yft-extensions.git" }
async-trait = "*"
